[rule]
enabled=true
name=sshd

# input
source=journal
programs=sshd
# programs=* # match all journal lines (disables program prefilter)
# source=file
# files=/var/log/auth.log,/var/log/secure

# detection
failregex=Failed password .* from (?P<ip>\S+)
failregex=Invalid user .* from (?P<ip>\S+)
ignoreregex=

# policy
findtime=600
maxretry=5
bantime=3600

# action (ban/detect)
action=ban
ports=all # all | 22,25 | 22-2222 | 8080

# Firewall backend:
#   auto      = prefer nft (if available), otherwise iptables
#   nftables  = force nft
#   iptables  = force iptables
backend=auto
